name: Accessibility Issue
description: Report an accessibility or usability issue.
title: '[A11y_Bug]: '
labels: 'type: A11y_Bug'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to fill out this accessibility report. IBM
        firmly believes that web and software experiences should be accessible
        for everyone. 
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What project are working with? 
      multiple: true
      options: 
        - 'able site'
        - 'accessibility-checker-engine'
        - 'extension-checker'
        - 'accessibility-checker for Node'
        - 'cypress-accessibility-checker'
        - 'karma-accessibility-checker'
        - 'other'
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      multiple: true
      options:
        - MacOS
        - Windows
        - Other
  - type: input
    id: tool
    attributes:
      label: Automated testing tool and ruleset.
      description: 'Which tool and ruleset uncovered the issue?'
      placeholder: e.g. IBM Equal Access Accessibility Checker - Latest Deployment
  - type: input
    id: technology
    attributes:
      label: Assistive technology
      description: 'Did you experience the issue using an assistive technology?'
      placeholder: e.g. JAWS, MacOS VoiceOver
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        "Tell us more about the accessibility issue that you're experiencing"
      placeholder: What did you expect to happen? What happened instead?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description:
        'How do we reproduce the accessibility violation you described?'
    validations:
      required: true
  
