name: 'Bug Report 🐛'
description: Report an issue.
title: '[BUG]: '
labels: 'type: Bug'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to fill out this bug report. 
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What project are working with? 
      multiple: true
      options: 
        - 'able site'
        - 'accessibility-checker-engine'
        - 'extension-checker'
        - 'accessibility-checker for Node'
        - 'cypress-accessibility-checker'
        - 'karma-accessibility-checker'
        - 'other'
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue with?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: Which operating system are you using?
      multiple: true
      options:
        - MacOS
        - Windows
        - Other
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        "Tell us more about the issue that you're experiencing"
      placeholder: What did you expect to happen? What happened instead?
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description:
        'How do we reproduce the issue you described using the?'
    validations:
      required: true
  
