name: EPIC template for Releases / Point Releases
description: This is a template for epics
title: '[EPIC]:'
labels: 'type: epic'
body:
  - type: markdown
    attributes:
      value: '## Epic Details'
  - type: textarea
    id: hill
    attributes:
      label: Hill
      description: "What does the user need – include some sort of WOW element"
    validations:
      required: true
  - type: textarea
    id: playback
    attributes:
      label: Playback Demonstration
      description: "What will you be able to show at the end of the release / point release to demonstrate how you accomplished your user story? If possible, list what you target to demonstrate for each sprint."
    validations:
      required: true
  - type: textarea
    id: metric
    attributes:
      label: Metric
      description: "How can we measure the impact of this change?"
    validations:
      required: true
  - type: textarea
    id: comms
    attributes:
      label: Comms
      description: "When completed, who should you communicate this change to, what will you tell them (concisely), and where?"
    validations:
      required: true
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: "What project are you working with?" 
      multiple: true
      options: 
        - 'able site'
        - 'accessibility-checker-engine'
        - 'extension-checker'
        - 'accessibility-checker for Node'
        - 'cypress-accessibility-checker'
        - 'karma-accessibility-checker'
        - 'other'
    validations:
      required: true
  - type: checkboxes
    id: tasks
    attributes:
      label: Tasks
      value: |
        ## (Definition of Done)
        - [ ] Results are added to the Release Mural with a description of what was accomplished, KPIs, etc
        - [ ] All content has been reviewed for grammar, spelling, style, and technical accuracy
        - [ ] All code committed to the main branch
        - [ ] All unit tests pass (including accessibility)
        - [ ] Demo works in the staging environment
        - [ ] At least one performance metric/monitor constructed
