name: 'Feature request or enhancement 💡'
description: Suggest an idea for this project.
title: '[Feature]: '
labels: 'type: enhancement'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to share your idea or enhancement. 
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: What project is this idea/enhancement for? 
      multiple: true
      options: 
        - 'able site'
        - 'accessibility-checker-engine'
        - 'extension-checker'
        - 'accessibility-checker for Node'
        - 'cypress-accessibility-checker'
        - 'karma-accessibility-checker'
        - 'other'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description:
        "Tell us more about your idea or enhancement"
      placeholder: Provide as much details for this idea?
    validations:
      required: true
