name: 'New rule research'
description: Create new rule or update existing.
title: '[Rule RSRCH]: '
labels: 'type: Engine'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to improve the rules that help accessibility checks. 
  - type: textarea
    id: rule_description
    attributes:
      label: Rule description
      description:
        "Briefly describe the rule applicability"
      placeholder: 'Example: This rule checks for the Persistent requirement of information displayed on hover. It applies to any content that through CSS is displayed as a result of :hover.'
    validations:
      required: true 
  - type: dropdown
    id: requirement
    attributes:
      label: Relevant requirement(s)
      description: Select the relevant requirement. [IBM requirements](https://www.ibm.com/able/requirements/requirements)
      multiple: true
      options: 
        - 1.1.1 Non-text Content
        - 1.2.1 Audio-only and Video-only (Prerecorded)
        - 1.2.2 Captions (Prerecorded)
        - 1.2.3 Audio Description or Media Alternative (Prerecorded)
        - 1.2.4 Captions (Live)
        - 1.2.5 Audio Description (Prerecorded)
        - 1.3.1 Info and Relationships
        - 1.3.2 Meaningful Sequence
        - 1.3.3 Sensory Characteristics
        - 1.3.4 Orientation
        - 1.3.5 Identify Input Purpose
        - 1.4.1 Use of Color
        - 1.4.2 Audio Control
        - 1.4.3 Contrast (Minimum)
        - 1.4.4 Resize Text
        - 1.4.5 Images of Text
        - 1.4.10 Reflow
        - 1.4.11 Non-text Contrast
        - 1.4.12 Text Spacing
        - 1.4.13 Content on Hover or Focus
        - 2.1.1 Keyboard
        - 2.1.2 No Keyboard Trap
        - 2.1.4 Character Key Shortcuts
        - 2.2.1 Timing Adjustable
        - 2.2.2 Pause, Stop, Hide
        - 2.3.1 Three Flashes or Below Threshold
        - 2.4.1 Bypass Blocks
        - 2.4.2 Page Titled
        - 2.4.3 Focus Order
        - 2.4.4 Link Purpose (In Context)
        - 2.4.5 Multiple Ways
        - 2.4.6 Headings and Labels
        - 2.4.7 Focus Visible
        - 2.5.1 Pointer Gestures
        - 2.5.2 Pointer Cancellation
        - 2.5.3 Label in Name
        - 2.5.4 Motion Actuation
        - 3.1.1 Language of Page
        - 3.1.2 Language of Parts
        - 3.2.1 On Focus
        - 3.2.2 On Input
        - 3.2.3 Consistent Navigation
        - 3.2.4 Consistent Identification
        - 3.3.1 Error Identification
        - 3.3.2 Labels or Instructions
        - 3.3.3 Error Suggestion
        - 3.3.4 Error Prevention (Legal, Financial, Data)
        - 4.1.1 Parsing
        - 4.1.2 Name, Role, Value
        - 4.1.3 Status Messages
        - 4.1.4 Accessibility-supported Technologies Only (IBM requirement)
        - 502.2.1 User Control of Accessibility Features
        - 502.2.2 No Disruption of Accessibility Features
        - 502.3.1 Object Information
        - 502.3.2 Modification of Object Information
        - 502.3.3 Row, Column, and Headers
        - 502.3.4 Values
        - 502.3.5 Modification of Values
        - 502.3.6 Label Relationships 
        - 502.3.7 Hierarchical Relationships
        - 502.3.8 Text
        - 502.3.9 Modification of Text
        - 502.3.10 List of Actions
        - 502.3.11 Actions on Objects
        - 502.3.12 Focus Cursor
        - 502.3.13 Modification of Focus Cursor
        - 502.3.14 Event Notification
        - 502.4 Platform Accessibility Feature
        - 503.2 User Preferences
        - 503.3 Alternative User Interfaces
        - 503.4.1 Caption Controls
        - 503.4.2 Audio Description Controls
        - 504.2 Content Creation or Editing
        - 504.2.1 Preservation of Information Provided for Accessibility in Format Conversion
        - 504.2.2 PDF Export
        - 504.3 Prompts
        - 504.4 Templates
        - 602.2 Accessibility and Compatibility Features
        - 602.3 Electronic Support Documentation
        - 5.2 Activation of Accessibility Features
        - 5.7 Key Repeat
        - 5.8 Double-strike Key Acceptance
        - 5.9 Simultaneous User Actions
        - 7.1.1 Captioning Playback
        - 7.1.2 Captioning Synchronization
        - 7.1.3 Preservation of Captioning
        - 7.1.4 Captions Characteristics
        - 7.1.5 Spoken Subtitles
        - 7.2.1 Audio Description Playback
        - 7.2.2 Audio Description Synchronization
        - 7.2.3 Preservation of Audio Description
        - 7.3 User Controls for Captions and Audio Description
        - 10.5 Caption Positioning
        - 10.6 Audio Description Timing
        - 11.5.2.3 Use of Accessibility Services
        - 11.8.4 Repair Assistance
        - 41.2.1 Sign Language Widget
    validations:
      required: true  
  - type: markdown
    attributes:
      value: '## The items below are optional and can be completed by the Checker team'
  
  - type: textarea
    id: High_level_approach
    attributes:
      label: High-level approach and rule scope
      description:
        "Provide a very high level summary of the rule approach and summary of the scope"
      placeholder: 'Example: Detect any hover of a target and flag a Needs Review potential violation to the Accessibility Checker user'  
  - type: dropdown
    id: ruleste 
    attributes:
      label: Ruleset and failure level
      description: Please select a ruleset version?
      multiple: true
      options:
        - WCAG 2.0
        - WCAG 2.1
        - IBM
  - type: dropdown
    id: failure_level
    attributes:
      label: Failure level
      description: Indicate the expected overall failure level
      multiple: true
      options:
        - Violation
        - Potential violations
        - Recommendation
  - type: textarea
    id: failure2nd
    attributes:
      label: Different failure level
      placeholder: If different rulesets result in different failure levels, note here.
  - type: textarea
    id: Failure_cases 
    attributes:
      label: Failure cases
      description:
        "Provide the steps of the rule logic"
      placeholder: Example
          1. Is :hover used? No, pass; Yes, proceed
          2. Is display being altered in relation with hover? No, pass; Yes, proceed
          3. Is the element affected by display a direct child of the trigger element (the one with hover) Yes, pass; No, PV
