/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ibm.able.util;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.IOException;

import com.ibm.able.util.Fetch;

public class FetchTest {
    @Test public void getArr() {
        String s = null;
        try {
            s = Fetch.get("https://cdn.jsdelivr.net/npm/accessibility-checker-engine@next/archives.json");
        } catch (IOException e) {
            e.printStackTrace();
        }
        assertEquals(String.class, s.getClass());
    }
}
