/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ibm.able;

import org.junit.Test;
import static org.junit.Assert.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
// import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import com.ibm.able.Library;

public class LibraryTest {
    private static ChromeDriver driver;

    /**
     * Setup a Selenium Chrome environment before tests
     */
    @BeforeClass public static void setup() {
        String workingDir = System.getProperty("user.dir");
        String chromeDriverDir = workingDir+"/src/test/resources/chromedriver-mac-arm64/chromedriver";
        System.setProperty("webdriver.chrome.driver", chromeDriverDir);
        LibraryTest.driver = new ChromeDriver();
    }

    /**
     * Close Selenium Chrome environment after tests
     */
    @AfterClass public static void teardown() {
        LibraryTest.driver.close();
    }

    @Test public void someLibraryMethodReturnsTrue() {
        LibraryTest.driver.get("https://altoromutual.12mc9fdq8fib.us-south.codeengine.appdomain.cloud/");
        String pageTitle = driver.getTitle();
        System.out.println("Page Title: " + pageTitle);        
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
